#!/bin/sh
#
# Startup Fedora and RedHat script for BGPmon.
#
# Author: Mikhail Strizhov
# strizhov@cs.colostate.edu
#
#
# chkconfig: 35 85 15     - start or stop process definition within the boot process
# description: BGPmon Monitoring System
# processname: bgpmon
# pidfile: /var/run/bgpmon.pid
SYSTEMCTL_SKIP_REDIRECT=1

# Source function library.      This creates the operating environment for the process to be started
. /etc/rc.d/init.d/functions

BGPMON=bgpmon
BINDIR=/usr/local/bin
STATEDIR=/var
BGPMON_EXEC=${BINDIR}/${BGPMON}
SYSCONFDIR=/etc
CONFIG_FILE=${SYSCONFDIR}/bgpmon_config.txt
GEODB_FILE=${SYSCONFDIR}/bgpmon_geodb.txt
STARTSTOPD=/sbin/start-stop-daemon
ARGS=" -c $CONFIG_FILE -d -s -g $GEODB_FILE"
lockfile=/var/lock/subsys/${BGPMON}

case "$1" in
  start)
	if pgrep -f ${BGPMON_EXEC} > /dev/null
	then
		echo "$BGPMON is running"
	else
	        echo -n "Starting $BGPMON: "
        	daemon $BGPMON_EXEC $ARGS
                RETVAL=$?
		echo
                [ $RETVAL -ne 0 ] && exit $RETVAL
                echo
		touch $lockfile
	fi	
        ;;
  stop)
	if pgrep -f ${BGPMON_EXEC} > /dev/null
	then
        	echo -n "Shutting down $BGPMON: "
	        killproc $BGPMON_EXEC
                echo
	        rm -f $lockfile
	else
		echo "$BGPMON is not running!"
	fi	
        ;;
 restart)
	$0 stop && $0 start
  	;;
 *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0

